# config/config.yaml

# Settings for the main application controller
application:
  # Number of cases to process concurrently. Should ideally match the number of available HPC GPUs.
  max_workers: 4
  # How often (in seconds) to scan the new_cases directory.
  scan_interval_seconds: 60
  # How often (in seconds) to poll the HPC for simulation completion.
  polling_interval_seconds: 300

# Paths to the external command-line tools P1 will orchestrate
executables:
  python_interpreter: "C:\\Python310\\python.exe"
  mqi_interpreter: "C:\\MOQUI_SMC\\mqi_interpreter\\main_cli.py"
  raw_to_dicom: "C:\\MOQUI_SMC\\RawToDCM\\moqui_raw2dicom.py"

# All file system paths, both local and remote.
paths:
  local:
    # P1 will watch this directory for new case subdirectories.
    scan_directory: "C:/MOQUI_SMC/new_cases"
    # Path to the application's central database file.
    database_path: "database/mqi_communicator.db"
    # The following paths use a {case_id} placeholder that will be dynamically replaced.
    # Directory for intermediate files (CSVs) generated by P2.
    processing_directory: "C:/MOQUI_SMC/data/cases/{case_id}/intermediate"
    # Directory to download raw simulation output from HPC.
    raw_output_directory: "C:/MOQUI_SMC/data/cases/{case_id}/raw"
    # Directory for final DICOM files generated by P3.
    final_dicom_directory: "C:/MOQUI_SMC/data/cases/{case_id}/dicom"
  hpc:
    base_dir: "~/MOQUI_SMC"
    tps_env_dir: "~/MOQUI_SMC/tps_env"
    output_csv_dir: "~/MOQUI_SMC/Output_csv/{case_id}"
    dose_raw_dir: "~/MOQUI_SMC/Dose_raw/{case_id}"

# Connection details for the HPC server.
hpc_connection:
  host: "mgmt01"
  port: 22
  user: "jokh38"
  # Using SSH keys is strongly recommended over passwords for security.
  ssh_key_path: "C:/Users/your_user/.ssh/id_rsa"